use std::collections::BTreeSet;
use std::path::Path;

fn main() {
    // Keep the LOCAL-window ACL allow-list (`allow-app-local`) in lockstep with the commands
    // registered in `generate_handler!`. New app/agent capabilities then become callable from the
    // trusted local windows (main, spotlight) automatically — no hand-editing the ACL — which is
    // what lets anything the user builds be used by the agents.
    //
    // The REMOTE-exposed subset (`allow-browser-remote` in permissions/app.toml) is deliberately
    // NOT touched here: it stays hand-curated, because that is the security boundary for untrusted
    // pages in the browser-panel webview and must never be auto-widened.
    //
    // Codegen must never break the build: on any parse problem we emit a warning and fall back to
    // the committed permissions/app_local.gen.toml.
    if let Err(e) = sync_local_command_acl() {
        println!("cargo:warning=allow-app-local codegen skipped ({e}); using committed list");
    }
    tauri_build::build()
}

/// Parse the command names out of the `generate_handler![ ... ]` block in src/lib.rs and write
/// them as the `allow-app-local` permission. Pure text parsing so it runs before the crate compiles.
fn sync_local_command_acl() -> Result<(), String> {
    println!("cargo:rerun-if-changed=src/lib.rs");
    let src = std::fs::read_to_string("src/lib.rs").map_err(|e| e.to_string())?;
    let commands = parse_handler_commands(&src)?;

    let mut toml = String::new();
    toml.push_str("# AUTO-GENERATED by build.rs from generate_handler! — DO NOT EDIT BY HAND.\n");
    toml.push_str("# Add a command to generate_handler! and it is automatically granted to the LOCAL\n");
    toml.push_str("# trusted windows (main, spotlight) on the next build — see capabilities/default.json\n");
    toml.push_str("# and spotlight.json. The remote-exposed subset is curated separately in app.toml\n");
    toml.push_str("# (allow-browser-remote) and is intentionally NOT generated.\n\n");
    toml.push_str("[[permission]]\n");
    toml.push_str("identifier = \"allow-app-local\"\n");
    toml.push_str(
        "description = \"Every registered app command; for local trusted windows only (auto-generated).\"\n\n",
    );
    toml.push_str("[permission.commands]\n");
    toml.push_str("allow = [\n");
    for c in &commands {
        toml.push_str("  \"");
        toml.push_str(c);
        toml.push_str("\",\n");
    }
    toml.push_str("]\n");

    let path = Path::new("permissions/app_local.gen.toml");
    // write-if-changed: avoid dirtying the working tree on no-op builds.
    if std::fs::read_to_string(path).unwrap_or_default() != toml {
        std::fs::write(path, &toml).map_err(|e| e.to_string())?;
    }
    Ok(())
}

/// Extract the command identifiers from the single `generate_handler![ ... ]` invocation.
/// Shared shape with the verification test in lib.rs.
fn parse_handler_commands(src: &str) -> Result<BTreeSet<String>, String> {
    const ANCHOR: &str = "generate_handler![";
    let start = src.find(ANCHOR).ok_or("generate_handler![ not found")? + ANCHOR.len();
    let len = src[start..].find(']').ok_or("handler ']' not found")?;
    let body = &src[start..start + len];

    let mut commands = BTreeSet::new();
    for raw in body.split(',') {
        // Drop trailing line comments, then take the final path segment (mail::mail_send -> mail_send).
        let token = raw.split("//").next().unwrap_or("").trim();
        let name = token.rsplit("::").next().unwrap_or("").trim();
        let mut bytes = name.bytes();
        let valid = match bytes.next() {
            Some(b) => (b.is_ascii_alphabetic() || b == b'_')
                && bytes.all(|b| b.is_ascii_alphanumeric() || b == b'_'),
            None => false,
        };
        if valid {
            commands.insert(name.to_string());
        }
    }
    if commands.is_empty() {
        return Err("no commands parsed from generate_handler!".into());
    }
    Ok(commands)
}
