// ─── Knowledge Health ─────────────────────────────────────────────────────────
// The companion to contextHealth.ts. That one asks "is the live window being
// managed well"; this one asks "is what I know still actually mine".
//
// Premise: a knowledge base that feeds an assistant, and is fed BY that
// assistant, is a closed loop — and closed loops drift. Measured behaviour in
// RAG systems without provenance tracking: a corpus starting at ~13% synthetic
// content reaches 50% within ~17 generations and stabilises around 72%. The
// dangerous part is that it is invisible while it happens — answer quality
// holds up, because fluency is preserved even as grounding drains away. So the
// erosion has to be MEASURED; it cannot be noticed.
//
// The structural guard against this lives in the Origin type (see
// docs/concept-canvas-design.md): `generated` content is retrievable but can
// never count as grounding, so the loop cannot close in the first place. This
// module is the monitor that proves the guard is holding — and catches the
// softer failures the guard doesn't cover:
//
//   - Grounded share falling while the library grows (generation outpacing reading).
//   - Few distinct sources carrying many concepts — "retrieval collapse" erodes
//     source diversity before it erodes accuracy.
//   - Claims resting on a single source, which is a fact only in the sense that
//     one page said so once.
//   - Citations that no longer match their source (an edited note, a rewritten page).
//   - Facets written by a model that has since been replaced — significant when
//     moving to local models, where an early small model may have written a lot.
//
// Deliberately NOT a fullness bar. Following contextHealth's framing: a high
// generated share is normal and healthy when you are exploring new territory —
// you simply haven't read yet. What is unhealthy is generated share RISING while
// nothing new comes in. Direction matters more than level, which is why a prior
// snapshot is an input rather than something inferred from a single reading.

export type KnowledgeHealthStatus = 'healthy' | 'exploring' | 'attention';

export type KnowledgeHealthRecId =
  | 'read-more'
  | 'diversify'
  | 'corroborate'
  | 'reverify'
  | 'regenerate-weak'
  | 'drifting';

export interface KnowledgeHealthRecommendation {
  id: KnowledgeHealthRecId;
  text: string;
}

/** A prior reading, so drift can be measured rather than guessed. */
export interface KnowledgeSnapshot {
  groundedPct: number;
  conceptCount: number;
  at: number;
}

export interface KnowledgeHealthInput {
  /** Concepts that currently exist in the library. */
  conceptCount: number;
  /** Blocks whose Origin is `read` or `authored` — the grounded ones. */
  groundedBlocks: number;
  /** Blocks whose Origin is `generated`. Retrievable, never grounding. */
  generatedBlocks: number;
  /** Blocks whose Origin is `contested`. Counted in the total, not as grounding. */
  contestedBlocks: number;
  /** Distinct sources (files/URLs) that ground at least one block. */
  distinctSources: number;
  /** Concepts grounded by exactly one source. */
  singleSourceConcepts: number;
  /** Grounded blocks whose stored quote no longer matches its source text. */
  staleCitations: number;
  /** Facets generated by a model no longer in use. */
  facetsFromRetiredModels: number;
  /** Epoch ms when something was last READ IN (page digest, dropped file). */
  lastReadAt?: number | null;
  /** A previous assessment, for drift. Omit on first run. */
  previous?: KnowledgeSnapshot | null;
  /** Injectable clock for tests. */
  now?: number;
}

export interface KnowledgeHealth {
  status: KnowledgeHealthStatus;
  /** Short chip label: "Healthy" / "Exploring" / "Needs tuning". */
  headline: string;
  /** One-line explanation of WHY — suitable for a tooltip or subline. */
  detail: string;
  /** Share of blocks that are grounded in something you read or wrote. */
  groundedPct: number;
  /** Concepts per distinct source. High means a few sources carry everything. */
  sourceLoad: number;
  /** Change in groundedPct since `previous`, or null on a first reading. */
  driftPct: number | null;
  recommendations: KnowledgeHealthRecommendation[];
  /** Snapshot to persist and pass back as `previous` next time. */
  snapshot: KnowledgeSnapshot;
}

const DAY_MS = 24 * 60 * 60 * 1000;

/** Nothing new read in this long, while the library keeps growing, is a drift risk. */
export const READ_STALE_MS = 14 * DAY_MS;
/** A fall in grounded share of at least this much means generation is outpacing reading. */
export const DRIFT_ATTENTION_PCT = 10;
/** Below this grounded share, the library is mostly the model talking to itself. */
export const GROUNDED_FLOOR_PCT = 25;
/** Above this grounded share, nothing needs saying. */
export const GROUNDED_HEALTHY_PCT = 55;
/** More concepts than this per distinct source means diversity is thin. */
export const SOURCE_LOAD_CEILING = 8;
/** Share of concepts resting on a single source before it's worth flagging. */
export const SINGLE_SOURCE_CEILING_PCT = 60;

const pct = (n: number, d: number) => (d <= 0 ? 0 : (n / d) * 100);
const round = (n: number) => Math.round(n);

export function assessKnowledgeHealth(input: KnowledgeHealthInput): KnowledgeHealth {
  const now = input.now ?? Date.now();

  const totalBlocks = Math.max(
    0,
    input.groundedBlocks + input.generatedBlocks + input.contestedBlocks,
  );
  const groundedPct = pct(input.groundedBlocks, totalBlocks);
  const sourceLoad = input.distinctSources <= 0
    ? input.conceptCount
    : input.conceptCount / input.distinctSources;

  const driftPct = input.previous ? groundedPct - input.previous.groundedPct : null;
  const grew = input.previous ? input.conceptCount > input.previous.conceptCount : false;

  const snapshot: KnowledgeSnapshot = {
    groundedPct,
    conceptCount: input.conceptCount,
    at: now,
  };

  const recommendations: KnowledgeHealthRecommendation[] = [];
  // Erosion signals — the library is getting less yours over time. These are the
  // ones the collapse research is about, and they can't be fixed by generating more.
  let eroding = false;

  // Drift is the primary signal: grounded share falling while the library grows is
  // exactly the closed-loop curve, caught early enough to matter.
  if (driftPct !== null && grew && driftPct <= -DRIFT_ATTENTION_PCT) {
    eroding = true;
    recommendations.push({
      id: 'drifting',
      text: `Your library grew, but the share grounded in what you've read fell ${round(Math.abs(driftPct))} points. Generation is outpacing reading — read into the concepts you've been unfolding.`,
    });
  }

  // An empty library is not unhealthy, it's new. Only judge a library with content.
  const hasContent = totalBlocks > 0;

  if (hasContent && groundedPct < GROUNDED_FLOOR_PCT) {
    const staleRead =
      input.lastReadAt == null || now - input.lastReadAt > READ_STALE_MS;
    // Low grounding while actively reading is exploration, not erosion. Low
    // grounding with nothing coming in is the thing to flag.
    if (staleRead) {
      eroding = true;
      recommendations.push({
        id: 'read-more',
        text: `Only ${round(groundedPct)}% of your library is grounded in something you read or wrote, and nothing new has come in recently. Unfold a concept and let Docent read into it.`,
      });
    }
  }

  if (input.distinctSources > 0 && sourceLoad > SOURCE_LOAD_CEILING) {
    eroding = true;
    recommendations.push({
      id: 'diversify',
      text: `${input.distinctSources} sources are carrying ${input.conceptCount} concepts. A narrow base reads as well-grounded but moves together — bring in something from outside it.`,
    });
  }

  const singlePct = pct(input.singleSourceConcepts, input.conceptCount);
  if (input.conceptCount > 0 && singlePct > SINGLE_SOURCE_CEILING_PCT) {
    recommendations.push({
      id: 'corroborate',
      text: `${round(singlePct)}% of your concepts rest on a single source. One page saying so isn't the same as it being settled — a second source is what makes it hold.`,
    });
  }

  if (input.staleCitations > 0) {
    eroding = true;
    recommendations.push({
      id: 'reverify',
      text: `${input.staleCitations} citation${input.staleCitations === 1 ? '' : 's'} no longer match the source text. Re-check them — a citation you can't verify is doing the opposite of its job.`,
    });
  }

  if (input.facetsFromRetiredModels > 0) {
    recommendations.push({
      id: 'regenerate-weak',
      text: `${input.facetsFromRetiredModels} passage${input.facetsFromRetiredModels === 1 ? ' was' : 's were'} written by a model you no longer use. Regenerate them on your current model — nothing is lost, since none of it was grounding anything.`,
    });
  }

  if (eroding) {
    return {
      status: 'attention',
      headline: 'Needs tuning',
      detail: recommendations[0].text,
      groundedPct,
      sourceLoad,
      driftPct,
      recommendations,
      snapshot,
    };
  }

  // Healthy-but-thin: plenty of the docent's own knowledge, but you're actively
  // reading into it. That's what learning something new looks like, and it must
  // not be reported as a problem.
  if (hasContent && groundedPct < GROUNDED_HEALTHY_PCT) {
    return {
      status: 'exploring',
      headline: 'Exploring',
      detail: `${round(groundedPct)}% grounded so far — you're into new territory, and reading is keeping up. This fills in as you go.`,
      groundedPct,
      sourceLoad,
      driftPct,
      recommendations,
      snapshot,
    };
  }

  if (!hasContent) {
    return {
      status: 'healthy',
      headline: 'Healthy',
      detail: 'Nothing in the library yet — unfold a concept to start.',
      groundedPct,
      sourceLoad,
      driftPct,
      recommendations,
      snapshot,
    };
  }

  return {
    status: 'healthy',
    headline: 'Healthy',
    detail: `${round(groundedPct)}% of your library is grounded in what you've actually read, across ${input.distinctSources} source${input.distinctSources === 1 ? '' : 's'}.`,
    groundedPct,
    sourceLoad,
    driftPct,
    recommendations,
    snapshot,
  };
}
